### ISSUE TITLE
Error installing BiocParallel

### ISSUE THREAD

**Issue by dcassol** [Bioconductor/BiocParallel#101]
Hi all, 
I'm having problems to install BiocParallel on Windows machine for testing. 
Please see bellow: 

##################
BiocManager::install("BiocParallel")
Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing package(s) 'BiocParallel'
trying URL 'https://bioconductor.org/packages/3.9/bioc/src/contrib/BiocParallel_1.18.0.tar.gz'
Content type 'application/x-gzip' length 928675 bytes (906 KB)
downloaded 906 KB

* installing *source* package 'BiocParallel' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'C:/Program Files/R/R-3.6.1/library/BiocParallel'
* restoring previous 'C:/Program Files/R/R-3.6.1/library/BiocParallel'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :

  problem copying C:\Program Files\R\R-3.6.1\library\00LOCK-BiocParallel\BiocParallel\libs\x64\BiocParallel.dll to C:\Program Files\R\R-3.6.1\library\BiocParallel\libs\x64\BiocParallel.dll: Permission denied

The downloaded source packages are in
        ‘C:\Users\Ken\AppData\Local\Temp\Rtmpy6hsjx\downloaded_packages’
Update old packages: 'BiocParallel', 'RcppArmadillo'
Update all/some/none? [a/s/n]:
a
Warning message:
In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘BiocParallel’ had non-zero exit status

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252   
 attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    
other attached packages:
[1] BiocParallel_1.17.18
loaded via a namespace (and not attached):
[1] BiocManager_1.30.4 compiler_3.6.1     parallel_3.6.1     tools_3.6.1        curl_3.3

**Comment by dcassol** [comment]
Also, you can see here some issue with CHECK on Linux and Windows machine!
[Screenshot from 2019-07-22 09-45-43](https://user-images.githubusercontent.com/12722576/61649168-c64b2a80-ac65-11e9-8b11-a8dc9c8221a4.png)
[http://bioconductor.org/checkResults/release/bioc-LATEST/BiocParallel/](BiocParallel)

**Comment by mtmorgan** [comment]
The installation problem is likely because on your machine there is already an R session running that is using BiocParallel. Quit all R sessions. Start one session and call

```
remove.packages("BiocParallel")
```
repeatedly until told that there are no versions to remove. Verify that you have succeeded in removing all packages by trying to load it
```
library("BiocParallel")
```
If it _does_ load, then it means that you have installed BiocParallel under another user account (e.g., system administrator) and your current account does not have permission to remove it. Quit the current R session, start R again under this account, and use `remove.packages("BIocParallel")` again.

Once you have removed all instances of BiocParallel, it should be possible to install it using `BiocManager::install("BiocParallel")`.

**Comment by dcassol** [comment]
Great! Thank you very much, @mtmorgan!
