### ISSUE TITLE
Have multicoreWorkers respect certain environment variables

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocParallel#116]
When choosing the number of workers, it would be nice for `multicoreWorkers` to respect the resource limits imposed by the scheduler on HPCs. For example, when I'm in an interactive job on Slurm with one alllocated CPU, I get way more CPUs than I'm allowed to access:

```r
BiocParallel::multicoreWorkers()
## [1] 54
```

I guess the problem is that `parallel:::detectCores()` doesn't respect the CPU masking, and maybe a better solution would be to improve the behavior of that function instead. But in the meantime,  we could have a more intelligent choice by using:

```r
Sys.getenv("SLURM_CPUS_ON_NODE")
## [1] "1"
```

I imagine that other schedulers would have equivalent environment variables. This would be a lightweight and transparent modification to `BiocParallel::multicoreWorkers()` (or `BiocParallel:::.detectCores`, if you also want to see it work for `SnowParam`):

```r
.detectCores <- function () {
    # Check for possible environment variables and return the first.
    possibilities <- "SLURM_CPUS_ON_NODE" # add more here for other schedulers.
    for (p in possibilities) {
         if (!is.na(chosen <- Sys.getenv(p, unset=NA))) {
              return(as.integer(chosen))
         }
    }

    result <- parallel::detectCores()
    result[is.na(result)] <- 1L
    max(1L, result - 2L)
}
```

This would be a quality-of-life improvement for me because I don't have to change both the Slurm submission script and the R script whenever I change the number of allocated cores.

<details>
<summary>Session information</summary>

```
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /gstore/apps/R/R_4.0.0_Bioc_3.12/R-4.0.0-Bioc-3.12-dev-20200504/lib64/R/lib/libRblas.so
LAPACK: /gstore/apps/R/R_4.0.0_Bioc_3.12/R-4.0.0-Bioc-3.12-dev-20200504/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.0      parallel_4.0.0      BiocParallel_1.23.0
```
</details>

**Comment by DarwinAwardWinner** [comment]
See also https://github.com/HenrikBengtsson/future/blob/develop/R/availableCores.R.

**Comment by mtmorgan** [comment]
A challenge is to understand what the correct solution is across environments, including those that I do not have access to. It's interesting for instance that @LTLA suggests `SLURM_CPUS_ON_NODE` but the future link uses `SLURM_CPUS_PER_TASK`.

BiocParallel respects `options("mc.cores")` so a straight-forward and adaptable solution is `options(mc.cores = Sys.getenv("SLURM_CPUS_ON_NODE", parallel::detectCores())`.

**Comment by HenrikBengtsson** [comment]
Hi. `future::availableCores()` and `future::availableWorkers()` exists for exactly this purpose and are designed to be developer, user, scheduler, hpc, and sysadm friendly.   They are designed such that they one day could be included in the {parallel} packages - because this is more general than specific "parallel" package.

They are designed such that developers and end-users should not have to configure this in scripts on shell environments - when users have to configure these things themselves there is a great risk that their scripts end up over subscribing the CPUs, e.g. someone writes a script for one environment and then pass it on and all of a sudden it wreak havoc on another system.  I see this on a daily basis at various work HPC environment.

Now, these functions are not set in stone.  On the contrary, they're open for discussion and improvements:

 * `availbleCores()`: https://github.com/HenrikBengtsson/future/issues/22
 * `availbleWorkers()`: https://github.com/HenrikBengtsson/future/issues/118

Personally, I don't have access to Slurm yet - only Torque/PBS and SGE - so the Slurm agility was added based on Slurm documentation.  I should get access to a solid Slurm cluster within 6-12 months.  I know that there are {future} users on Slurm (via {future.batchtools}) who have used it but I don't recall if there has a been a discussion regarding `availableCores()`.  I think people have also used it indirectly via {drake}.  So, it might very well be that the agility of Slurm needs to be updated/fixed.

**Comment by HenrikBengtsson** [comment]
Regarding `parallel::detectCores()`: Note that it may return `NA_integer_`.

(I'm also not a big fan of that function because it's too widely used without understand the implications of hard coding it as the default number of cores. This is especial bad since R Core are not interested in giving sysadms a backdoor for disabling or overriding the value in an easy way.  So, using it explicitly in code/packages helps contributing to oversubscribed CPUs on multi-tenant environments.  This is not just R, the same problem occurs in other pipelines from other languages)

**Comment by LTLA** [comment]
I suspect Slurm's environment variables change every now and then across releases, which is a bit of a pain as I'm never sure whether various online tutorials are going to work or not. It would well be that the current environment variable in `availbleCores()` worked for some version of Slurm.

Anyway, my immediate problem is solved by asking the administrator of our R installation to add:

```r
if (!is.na(val <- Sys.getenv("SLURM_CPUS_ON_NODE", NA))) options(mc.cores=val)
```

... to the system-wide `.Rprofile`. This should fire when R is run inside a Slurm job and set the default number of cores appropriately for **BiocParallel**-dependent applications. Probably something that could be added to the vignette, though I need to actually check if it works or not.

I'll further note that, at least on my cluster, OpenMP does successfully detect the number of cores that it has access to within a Slurm job. IIRC this is done on our system (and probably many others) with cgroups, so perhaps an "easy" win for `parallel::detectCores()` would be to respect that.
