### ISSUE TITLE
Virtual memory problems with BatchtoolsParam, cluster="multicore"

### ISSUE THREAD

**Issue by twillis209** [Bioconductor/BiocParallel#118]
Hello

I am using `BatchtoolsParam` to use a multicore backend on a SGE cluster, but my jobs are invariably killed on the cluster because their usage of virtual memory blows up, beyond that permitted by the cluster. I'm not sure if this is a problem with the cluster's administration, my usage of `BiocParallel`, or the code I am calling from the `zinbwave` package.

I am `qsub`ing an R program containing the following:

```
param <- BatchtoolsParam(workers=4,
                        cluster="multicore",
                        progressbar=T,
                        log=T,
                        registryargs=batchtoolsRegistryargs(
                                file.dir=paste("/nobackup", Sys.getenv("USER"), "simulateAllenData", sep="/"),
                                work.dir=paste(Sys.getenv("HOME"), "zinb_analysis/sims/figures", sep="/")
                                ))
```

I am passing param as an argument to the `zinbFit` function from the `zinbwave` package. I am running this code in an SMP parallel environment with four cores on the cluster. The virtual memory used by the job grows over time, no matter how high I set `h_vmem` in my queue submissions, until the job is killed by SGE. 

I have tried using `cluster="sge"` instead as documented in the vignette, but each section of parallelised code results in a new queue submission and is thus very slow, hence my trying `cluster="multicore"` instead. It's my understanding that queue submissions for each `bplapply` etc. with `cluster="sge"` is nonetheless the expected behaviour.

I have also tried `MulticoreParam` instead of `BatchtoolsParam`, but have encountered the same problem.

Apologies if this does not belong here, but I have struggled to find a solution to this as documentation of the same problem on the web is scant.

**Comment by DarwinAwardWinner** [comment]
If you're using a multicore backend, have you tried MulticoreParam?

**Comment by twillis209** [comment]
Yes, but I encounter the same problem unfortunately: the job is killed for exceeding the limit of virtual memory usage. In particular, I will typically request four cores, 8GB per core, and specify maximum virtual memory per core of 40GB. I have succesfully run this code on my own two-core, 12GB laptop.

**Comment by twillis209** [comment]
P.S. I do appreciate the speedy reply.

**Comment by HenrikBengtsson** [comment]
It looks like [zinbwave](https://bioconductor.org/packages/release/bioc/html/zinbwave.html) is using BiocParallel to parallelize internally.  Could it be that you are ended up with nested multicore parallelization here?  It's just a guess.

I don't know how BiocParallel handles such calls but from a quick test with nested `BiocParallel::bplapply()` calls will parallelize at each level and not just the top level:

```r
library(BiocParallel)
register(MulticoreParam(4))  ## <= all layers make use of this

foo <- function(x, ppid) { data.frame(x=x, pid=Sys.getpid(), ppid=ppid) }
bar <- function(X, pid=Sys.getpid()) do.call(rbind, bplapply(X, FUN = foo, ppid=pid))

y <- do.call(rbind, bplapply(rep(list(1:4), times=4), FUN = bar))
print(y)
##    x   pid  ppid
## 1  1 22790 22786
## 2  2 22792 22786
## 3  3 22795 22786
## 4  4 22797 22786
## 5  1 22791 22787
## 6  2 22793 22787
## 7  3 22796 22787
## 8  4 22798 22787
## 9  1 22794 22788
## 10 2 22800 22788
## 11 3 22803 22788
## 12 4 22805 22788
## 13 1 22799 22789
## 14 2 22801 22789
## 15 3 22802 22789
## 16 4 22804 22789
```

If the first layer of `bplapply()` would parallelize with MulticoreParam and the second with SerialParam, then `pid` == `ppid` (parent pid) for each entry.  Instead, we see that for each unique `ppid` (== one forked process) in turn spawn of parallel processes.

**Comment by twillis209** [comment]
That's very helpful, Henrik. 

I suspect this was naive of me, but I thought I could configure a `MulticoreParam()` backend in accordance with my submission to the cluster (e.g. four workers if I have requested four cores), then pass this MulticoreParam as the BPPARAM argument and the package code would take care of the rest.

It's noteworthy that I did not encounter the VRAM problems when running the toy pi approximation example from the BiocParallel vignette.

**Comment by HenrikBengtsson** [comment]
Just to clarify: My comment was just a hypothesis, not a fact. We need the BiocParallel developers to pitch in to know more.

**Comment by DarwinAwardWinner** [comment]
It's hard to say whether you're getting accidental recursive multicore spawning without seeing your full code. But generally, if zinbwave is using BiocParallel internally, then you should be fine as long as you aren't calling `bplapply` or anything else in your own code. Just register the param, and zinbwave should use it automatically.

Anyway, I'm not familiar enough with virtual memory to offer any useful advice here. Perhaps the issue is the forking behavior in the multicore backend, and using a non-forking parallel backend would work better? The downside is you'll have to be careful about writing your code, since the parallel workers won't automatically inherit your entire R environment.

**Comment by twillis209** [comment]
Thanks again.

I was reluctant to post the application code here as I was not sure that this was the venue for that, especially as my problem may be particular to `zinbwave` rather than `BiocParallel`. I am passing *Param objects to functions from the package and not trying to write any parallel code in my own right. I understand that passing the *Param objects in this way is equivalent to using `register`, or?

What you say about the backend is interesting, but doing anything other than choosing a different backend from `BiocParallel` is really beyond my ken.

**Comment by DarwinAwardWinner** [comment]
Yes, passing the param explicitly is equivalent to using register, unless the package developer has intentionally overridden that behavior. As for a non-forking parallel backend, I think the one to try would be SnowParam.

**Comment by mtmorgan** [comment]
@HenrikBengtsson FWIW BPPARAM can be a list containing the params to be applied at each level of nesting
```
y <- local({
    ## use a local environment to avoid problems serializing to workers
    bpparams = list(SnowParam(4), MulticoreParam(4))
    bplapply <- BiocParallel::bplapply
    foo <- function(x, ppid) {
        data.frame(x=x, pid=Sys.getpid(), ppid=ppid)
    }
    bar <- function(X, pid=Sys.getpid(), BPPARAM) {
        result <- bplapply(X, FUN = foo, ppid=pid, BPPARAM = BPPARAM)
        do.call(rbind, result)
    }
    result <- bplapply(rep(list(1:4), times=4), FUN = bar, BPPARAM = bpparams)
    do.call(rbind, result)
})
```
Creates 4 snow workers (e.g., on different machines) each of which use 4 multicore workers.

I don't really follow your pid / ppid; forked or spawned processes each get their own pid at least on macOS.
```
> str(bplapply(1:2, function(...) Sys.getpid(), BPPARAM = SnowParam(2)))
List of 2
 $ : int 13510
 $ : int 13519
> str(bplapply(1:2, function(...) Sys.getpid(), BPPARAM = MulticoreParam(2)))
List of 2
 $ : int 13530
 $ : int 13531
```

**Comment by twillis209** [comment]
Will I benefit from running `SnowParam()` in a shared memory parallelism environment on SGE (i.e. `-pe smp n`)? That is, it's not necessary for each worker to be a separate host? I had associated `SnowParam()` with MPI, but I see that the default cluster argument for `SnowParam` is `SOCK`, not `MPI`.

**Comment by mtmorgan** [comment]
For the original question, using `BatchtoolsParam()` with any type uses Batchtools with it's underlying database approach to distributing tasks. I don't think `multicore` is what you want -- it'll run jobs on the same node as forked processes; I guess this is why you see the same effect as MulticoreParam() -- the underlying zinbwave is not effectively controlling memory in each process.

Using `sge` is probably appropriate for a cluster environment where you want to use separate nodes, but as you note the 'data transmission' (i.e., starting nodes on a cluster) far outweigh the benefit in computation time. really you'd like to do a lot of computation on very little data transfer.

I'm a little rusty on this, but it might help to start the param first before passing to zinbwave; I think `bpstart()` gets you a  set of nodes to communicate with.
```
bpstart(param)  ## queue and start a bunch of workers
bplaply(...)    ## use the workers
bpstop(param)
```
I'd bet that this will still not be effective with zinbwave, where probably they were thinking of processing on a single node so didn't think about the cost of data transfer between machines.

My guess would be that the best strategy would be to explore the space a little, measuring how much memory zinbwave requires without parallelization for a few problem sizes (spanning an order of magnitude, say, from 'pretty fast' to 'edge of tolerably fast'). Then repeat with simple MulticoreParam(2) and compare both speed and memory consumption. This might point to basic problems with parallelization in zinbwave, at least in terms of managing memory use.

Also, a typical problem is how the problem scales with size -- if it is more than linear, then it will be very hard to tackle large problems regardless of compute power.

**Comment by mtmorgan** [comment]
Naively, on a single node that supports it, MulticoreParam() seems like a better choice -- forking is a much lighter-weight operation compared to spawning a new process, and one can pay much less attention to making sure data is available to all spawned workers. But actually for substantial computations, R will gradually duplicate a large chunk of the memory in the master environment; this sounds a bit like what is happening in your scenario. SnowParam() on the other hand makes you realize memory costs immediately, and can often be a better overall approach.

If using SnowParam, and having looked just briefly at zinbwave, it would really help to `bpstart()` the param before passing it to zinbwave -- there are several independent calls to `bplapply()` and each would otherwise pay the cost of spawning workers.

**Comment by HenrikBengtsson** [comment]
(Feel free to move this discussion to a separate issue because it might not be what's going on here)

@mtmorgan, my point is, if `BPPARAM` is not explicitly set, then the default will be `bpparam()`, which is whatever the user has registered via `BiocParallel::register()`.  Now, if there are nested `bplapply()` calls that don't use `BPPARAM` and that the end-user is not aware of, then `bpparam()` will keep using the registered backend all the way down (at least for MulticoreParam).

For example, if the user set `register(SerialParam())` you would effectively get:
```r
bpparams <- list(SerialParam(), SerialParam())
```
in your example that uses an explicit `BPPARAM`.  However, if the user set `register(MulticoreParam())`, it's as if you used:
```r
bpparams <- list(MulticoreParam(4), MulticoreParam(4))
```
whereas I argue the nested layers of parallelization should be resolved as:
```r
bpparams <- list(MulticoreParam(4), SerialParam())
```

If you peel off all your `BPPARAM` arguments from your example and use `register(SerialParam())` and `register(MulticoreParam(4))`, you'll see the same results. The same seems to be true if you use `register(SnowParam(4))`.

**Comment by mtmorgan** [comment]
@HenrikBengtsson yes of course, if you go with the default the current implementation uses the same param repeatedly and that could be wrong (probably nested parallelism is impossible to 'do the right thing' in package code where one has no idea what the user's compute environment might be, including use of other forms of parallelism, e.g., at the C level; maybe the only 'safe' choice is SnowParam()). I was only illustrating that there is a way to specify nesting, if you're in complete control of the parallel environment. I doubt that zinbwave's implementation is effective in any way other than MulticoreParam() (or perhaps with BPPARAM = bpstart(SnowParam())).

My confusion with your answer was trying to understand how pid / ppid would distinguish between forms of parallelism, since forked and spawned processes both share the master as ppid and have their own pid.

I don't think there are nested calls to bplapply in zinbwave; I think probably there is memory duplication and 8GB per core is simply not enough. I would not be surprised if the problem @twillis209 is experiencing is really an implementation challenge for the size of data to be analyzed

@twillis209 it might be better to ask on https://support.bioconductor.org where the zinbwave author and others can contribute...

**Comment by twillis209** [comment]
Thank you everyone for your responses, you have been very helpful.

**Comment by Jiefei-Wang** [comment]
close due to no more questions from the author
