### ISSUE TITLE
Where the workers can write files that are guaranteed to be accessible from the head node?

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocParallel#126]
I have a bad feeling there is no such place in general but I thought I would still ask.

Here is an artificial example where the workers need to write results to files. (See https://github.com/Bioconductor/DelayedArray/issues/76 for a real world use case.) In this artificial example, we want each worker to write random numbers to a file. Then, in the parent process, we want to collect all the numbers from all the files:

```
library(BiocParallel)

FUN <- function(i)
{
    x <- runif(1e6)
    rds_file <- tempfile(fileext=".rds")
    saveRDS(x, rds_file)
    rds_file
}
```

Works fine with MulticoreParam:
```
BPPARAM <- MulticoreParam(workers=2)

rds_files <- bplapply(1:5, FUN, BPPARAM=BPPARAM)

## All the workers used the tempdir() of the parent process:
rds_files
# [[1]]
# [1] "/tmp/Rtmpa2ChWu/file12fb3c1ff0d0.rds"
#
# [[2]]
# [1] "/tmp/Rtmpa2ChWu/file12fb774874cc.rds"
#
# [[3]]
# [1] "/tmp/Rtmpa2ChWu/file12fc3c1ff0d0.rds"
#
# [[4]]
# [1] "/tmp/Rtmpa2ChWu/file12fc774874cc.rds"
#
# [[5]]
# [1] "/tmp/Rtmpa2ChWu/file12fc67b9aada.rds"

tempdir()
# [1] "/tmp/Rtmpa2ChWu"

sapply(rds_files, file.exists)
# [1] TRUE TRUE TRUE TRUE TRUE
```

But not with SnowParam:
```
BPPARAM <- SnowParam(workers=2)

rds_files <- bplapply(1:5, FUN, BPPARAM=BPPARAM)

## Each worker used its own tempdir() that is different from the "main" tempdir():
rds_files
# [[1]]
# [1] "/tmp/RtmpiP5ngw/file132453f1a575.rds"
#
# [[2]]
# [1] "/tmp/RtmpiP5ngw/file13245db079ab.rds"
#
# [[3]]
# [1] "/tmp/Rtmp2HBijO/file132e4d6ccbef.rds"
#
# [[4]]
# [1] "/tmp/Rtmp2HBijO/file132ea0e6d55.rds"
#
# [[5]]
# [1] "/tmp/Rtmp2HBijO/file132e46b92777.rds"

sapply(rds_files, file.exists)
# [1] TRUE TRUE TRUE TRUE TRUE

## The files are easily destroyed (and in practice, in a real world situation, they will
## typically get destroyed before the parent process has a chance to access them):
gc()
sapply(rds_files, file.exists)
# [1] FALSE FALSE FALSE FALSE FALSE
```

So I wonder what's a reliable place where the workers can write files that are guaranteed to be accessible from the head node? I'm not sure it's even realistic to hope that such a place will always exist since I've been told that with some cluster configurations the nodes don't have access to the same file system as the head's.

Couldn't find any information about this in BiocParallel's documentation.

Thanks

**Comment by mtmorgan** [comment]
I don't think there's a guaranteed place, but in practice as Aaron indicates the user home directory is commonly shared across nodes.

**Comment by HenrikBengtsson** [comment]
FWIW, another model is to assume that the current working directory is shared (which I tend to use in my work).  Some systems have a dedicated global scratch space that are accessible from all hosts.  In such cases you can use:

```sh
$ cd /home/$USER/project
$ ln -s "/global/scratch/$USER" scratch
$ qsub -cwd myscript.sh
```

such that `./scratch/` is shared among workers and main.  That avoids having to hardcode /global/scratch/$USER into the code, or whatever the current system provides.  If all you have that is shared is the pwd, then you can use:

```sh
$ cd /home/$USER/project
$ mkdir scratch
$ qsub -cwd myscript.sh
```

without having to update the code.


PS. Now, a much more complicated problem is "synchronicity"; if workers and main are going to communicate data live via the file system (e.g. via a shared HDF5 file), then one needs to consider latency on this file system in order to make sure this works robustly.  My favorite example is NFS - it can take up to 30 seconds for a file to created on one host to be visible on another.  I'm not sure OS file locks are sufficient to protect against that.  The main problem here is that it's really hard to reproduce and troubleshoot when these problems occur, so it's also very hard to get right.

**Comment by mtmorgan** [comment]
I'll mention a purely cloud-based environment, where the notion of a shared disk across nodes might be completely irrelevant. This cloud-based system is implemented using BiocParallel with [RedisParam](https://github.com/mtmorgan/RedisParam) as used in [k8sredis](https://github.com/Bioconductor/k8sredis). (One could add a file system to the Kubernetes deployment, of course, but that's not really in the spirit of things...).

**Comment by hpages** [comment]
Thanks Martin, Henrik, for the discussion. Would be nice to see this discussed somewhere in BiocParallel's documentation.

**Comment by HenrikBengtsson** [comment]
> Would be nice to see this discussed somewhere in BiocParallel's documentation.

That's a big documentation task - because there are so many use cases to cover.  This problem also borders the problem with non-exportable objects, which is a complex task to document.  I'm touching upon the file-system problem in https://cran.r-project.org/web/packages/future/vignettes/future-7-for-package-developers.html with a "smell test" but just enough to tease the developer to become aware of the problem.

**Comment by hpages** [comment]
Thanks Henrik for the pointer. I was not aware of the future package. Looks interesting.
