### ISSUE TITLE
fails to assign values in data.table

### ISSUE THREAD

**Issue by shubham1637** [Bioconductor/BiocParallel#131]
`data.table` objects can be modified by reference and don't get recreated while get modified inside functions. I get to have this behavior if I modify list of data.table with `lapply`. However, I don't get this behavior with `BiocParallel::bplapply`:

```
library(data.table)
l = list(data.table(x = letters[1:3], y = 1),
         data.table(x = letters[3:5], y = 2))
function1 <- function(DT){
  DT[x == "b", y := 10]
  function2(DT)
  invisible(NULL)
}

function2 <- function(DT){
  DT[x == "c", y := 100]
  invisible(NULL)
}
invisible(lapply(l, function(df) function1(df)))
l

[[1]]
   x   y
1: a   1
2: b  10
3: c 100

[[2]]
   x   y
1: c 100
2: d   2
3: e   2
```
With BiocParallel:

```
l = list(data.table(x = letters[1:3], y = 1),
         data.table(x = letters[3:5], y = 2))
library(BiocParallel)
BiocParallel::MulticoreParam()
invisible(BiocParallel::bplapply(l, function(df) function1(df)))
l

[[1]]
   x y
1: a 1
2: b 1
3: c 1

[[2]]
   x y
1: c 2
2: d 2
3: e 2
```
Is there a way to fix it?

**Comment by DarwinAwardWinner** [comment]
I think this is probably not fixable. You are using `lapply` to call a function for its side effects rather than its return value, and this is generally not compatible with how BiocParallel works. However, it seems that data.table already supports thread-based parallelism natively, which I think will likely give much better speed for such operations. You should probably use that if you are able to do so in your setting.

**Comment by shubham1637** [comment]
Thanks for your comment @DarwinAwardWinner . The non-supported nature of BiocParallel is also due to `data.table` as it doesn't support split-apply-combine, as mentioned [here](https://stackoverflow.com/a/14763642/6484844):

**Comment by mtmorgan** [comment]
A fun exploration would use the [SharedObject][1] package to share the list between R sessions; I don't know how this works with data.table; maybe @Jiefei-Wang knows? It seems to do the trick...
```
> ls = SharedObject::share(l)
> invisible(BiocParallel::bplapply(ls, function(df) function1(df)))
> ls
[[1]]
   x   y
1: a   1
2: b  10
3: c 100

[[2]]
   x   y
1: c 100
2: d   2
3: e   2
```

[1]: https://bioconductor.org/packages/SharedObject

**Comment by Jiefei-Wang** [comment]
Thank @mtmorgan for bringing this interesting question. Usually, `SharedObject` respects R's copy-on-write(COW) semantic by allowing R to duplicate its data, so if you change the values of a shared object in a process, it would not affect the values of the same object in another process for R will duplicate the shared object and have a local copy of the object before you make the change. However, if an object is designed to behave like a reference(e.g. environment), R would not duplicate the object when it sees changes. Therefore, if you make changes to such object, the duplication is never triggered, so the change will directly go to the shared memory and become visible by the all workers. That's why we have this fantastic output here.

While the result looks surprising, I think this is a good feature in `SharedObject`. If your object respects COW, the shared object also respects it. If you break COW intentionally, you also get the same behavior on the shared object.

Cheers,
Jiefei

**Comment by shubham1637** [comment]
@j

**Comment by shubham1637** [comment]
@Jiefei-Wang  When I try to use SharedObject for character, it says:
```
Error: The object of the class <character> cannot be shared.
To suppress this error and return the same object, 
provide `mustWork = FALSE` as a function argument
or change its default value in the package settings
```
If I set `mustWork = FALSE`, then `bplapply` gives this error:
```
Error: attempt to select less than one element in OneIndex
Backtrace:
 1. DIAlignR::alignTargetedRuns(...) test_align_dia_runs.R:36:2
 3. BiocParallel:::applyFun(1:20, function(i) FUN(i))
 5. BiocParallel::bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
 7. BiocParallel:::bploop.lapply(cls, X, lapply, ARGFUN, BPPARAM)
```

**Comment by Jiefei-Wang** [comment]
Hi @shubham1637, sorry for the late reply. I believe you are using the old version of SharedObject. We do support character in the latest version.

**Comment by mtmorgan** [comment]
closing as no longer a BiocParallel issue.
