### ISSUE TITLE
Looking for suggestions for the BiocParallel for Bioc 3.15

### ISSUE THREAD

**Issue by Jiefei-Wang** [Bioconductor/BiocParallel#160]
Hi all,

Since Bioc 3.15 is coming soon, we are preparing for the next devel branch for BiocParallel. I would like to take this chance to discuss what new features, bug fixes, or changes in behavior we can achieve in the next devel version. Both experiences from the user and developer are welcome. Please feel free to leave any comment under this issue.

Cheers,
Jiefei

**Comment by Jiefei-Wang** [comment]
Since I started the topic, I'll take this advantage and leave my two cents here. We can give a better error handling mechanism in `bpiterate` and allow the function to redo the parallel evaluation when the error occurs. The current devel version cannot correctly process the error, for example
```
iter_factory <- function(n){
    i <- 0L
    function(){
        i <<- i + 1L
        if(i > n)
            NULL
        else if(i == 2L)
            as.character(i)
        else
            i
    }
}

## Not working
bpiterate(iter_factory(3), identity, REDUCE = `+`)
## Error in ..., non-numeric argument to binary operator

## Not working neither, it does not return a BPREDO
bptry(bpiterate(iter_factory(3), identity, REDUCE = `+`))
## Error in ..., non-numeric argument to binary operator
```
If this is a long-running job, the cost of redoing everything will be significant. I guess this can justify enough why we need this feature.

**Comment by HenrikBengtsson** [comment]
(disclaimer: I'm the author) Since you asked :p, adding native support for [futures](https://www.futureverse.org/) would be great.   This would make **BiocParallel** work on all top of future-based parallel/distributed backends.  This would require implementing support once, and it will automagically work with all current and future (pun intended) future backends automagically, because futures work the same regardless of parallel backend.

I started [**BiocParallel.FutureParam**](https://github.com/HenrikBengtsson/BiocParallel.FutureParam/) as a rudimentary proof-of-concept a while ago.  However, in order for me to invest more time in it, I'd like to see some interest for built-in support of futures in **BiocParallel**.

**Comment by mtmorgan** [comment]
I'll close this issue since Bioc 3.15 has been released.
