### ISSUE TITLE
`bplapply` with `SerialParam` doesn't behave nicely with `debug`

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/BiocParallel#168]
`debug`ing the `bplapply`'d function doesn't work anymore.

```r
library(BiocParallel)
x <- function(i) { stop(i) }
debug(x)
bplapply(1:5, x, BPPARAM=SerialParam())
## Browse[2]>
## Browse[2]> i
## Browse[2]>
```

I only see the actual `debug` output after the function returns. What I expected was the below. (Do this in a fresh R session, because if you `Q`uit the debug mode within `bplapply()`, it'll break the printing for the entire session.)

```r
x <- function(i) { stop(i) }
debug(x)
lapply(1:5, x)
## debugging in: FUN(X[[i]], ...)
## debug at #1: {
##     stop(i)
## }
## Browse[2]> i
## [1] 1
## Browse[2]>
## debug at #1: stop(i)
## Browse[2]> 
## Error in FUN(X[[i]], ...) : 1
```

I don't know what changed, but it certainly makes it difficult to debug functions within `bplapply` blocks. This isn't even a question of parallelization - with `BPPARAM = SerialParam()`, I would have expected it to be an exact replacement for `lapply`.

<details>
<summary>Session information</summary>

```
R version 4.1.0 Patched (2021-05-20 r80347)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/R-4-1-branch-dev/lib/libRblas.so
LAPACK: /home/luna/Software/R/R-4-1-branch-dev/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocParallel_1.28.0

loaded via a namespace (and not attached):
[1] compiler_4.1.0 parallel_4.1.0
```
</details>

**Comment by Jiefei-Wang** [comment]
Thanks for the catch, I think that's due to the `sink` function in

https://github.com/Bioconductor/BiocParallel/blob/bb94ba1a07bbd41d83b94a184ed5b603065e3584/R/bploop.R#L32-L58

I'm not sure why the message is captured by the variable `file` but not used by the subsequent code. Perhaps stale code @mtmorgan?

**Comment by mtmorgan** [comment]
I guess SerialParam() used to just `lapply()` but now uses a more complicated machinery to avoid code duplication while supporting, e.g., error logging. `sout` is used in line 56, returning output to the master for local logging. I'm not sure how to fix this...

**Comment by HenrikBengtsson** [comment]
In **future**, I "solve" this by making it an option to pass `split = TRUE` to `sink()` when setting up the backend. The downside is that output from the browser will also be captured. This can also be used with **batchtools**, where some like to see batchtools output in the job log file(s).

FYI, I also suggest staying far away from sinking _stderr_ (`type = "message"`). The reason is that there can only be one such sink in an R process, but it's not clear who may own it (=> no one may own it and it cannot be used in any package). This problem is further illustrated in https://github.com/HenrikBengtsson/Wishlist-for-R/issues/55.

To catch messages, one can use a calling handler, to catch the actual `message` objects. I do this in **future**, where I catch all types of `condition` objects by default, and relay them later in the main R session.

One more thing, `textConnection()` becomes ridiculously slow as the buffered size grow. You can use a `rawConnection()` to avoid this. See https://www.jottr.org/2014/05/26/captureoutput/ for benchmarks.

Clear as mud?

**Comment by mtmorgan** [comment]
Thanks for the bug report, and for comments @HenrikBengtsson. We didn't use `split=` but instead only use sink() when not in SerialParam(). We also didn't avoid sink() on the message stream. For one thing, we're interested in capturing stderr, not just messages; we appreciate that we're playing with fire here, but it is on the workers so damage will be relatively localized (incomplete message capture to the manager).

We use a raw connection to improve performance when there's a large amount of output; for some reason I had thought this behavior of textConnection had been fixed, but apparently not...
