### ISSUE TITLE
timeout & bpoptions

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocParallel#193]
It seems like `timeout` 'works' the first time
```{r}
> opts <- bpoptions(timeout = 1)
> bplapply(
+ 1:2, function(x) Sys.sleep(2), BPPARAM = p, BPOPTIONS = opts
+ )
Error: BiocParallel errors
  1 remote errors, element index: 1
  1 unevaluated and other errors
  first remote error:
Error in Sys.sleep(2): reached elapsed time limit
```
but not subsequently?
```{r}
> bplapply(
+ 1:2, function(x) Sys.sleep(2), BPPARAM = p, BPOPTIONS = opts
+ )
[[1]]
NULL

[[2]]
NULL
```

**Comment by Jiefei-Wang** [comment]
Thanks, this is not the issue of `bpoptions`. It looks like the `timeout` setting is broken. It still works with `SerialParam` but does not work with `SnowParam`.

```
p <- SnowParam(2, timeout = 1, exportglobals = F)
bplapply(1:2, function(x) {
    Sys.sleep(2)
}, BPPARAM = p)
# [[1]]
# NULL
# 
# [[2]]
# NULL
```
but this is a weird issue because everything looks good if I pull all data from the workers.
```
p <- SnowParam(2, timeout = 1, exportglobals = F)
frames <- bplapply(1:2, function(x) {
    Sys.sleep(2)
    sys.frames()
}, BPPARAM = p)

firstTask <- frames[[1]]
## .workerLapply_impl
names(firstTask[[19]])
# c("args", "composeFunc", "state", "X", "FUN", "ARGS", "OPTIONS", "BPRNGSEED")

args <- firstTask[[19]]$args
do.call(lapply, args)
# [[1]]
# <remote_error in Sys.sleep(2): reached elapsed time limit>
#     traceback() available as 'attr(x, "traceback")'
```
I have no clue why this could happen, any thought?

**Comment by mtmorgan** [comment]
I agree that this seems like a timeout issue unrelated to bpoptions. From `?setTimeLimit` I don't really see how this could work anyway, since the workers are never evaluating commands at the top level.

**Comment by Jiefei-Wang** [comment]
I guess it should work for

1. In the document, it states `If it is called from within a computation the limits apply to the rest of the computation `

2. It works with `SerialParam` and `MulticoreParam`

I just do not understand why `SnowParam` becomes a special case and it works occasionally as well(Just as your example). I have to think about it for a while.

**Comment by Jiefei-Wang** [comment]
I think this is the issue is related to `Sys.sleep` since the following code works

```
p <- SnowParam(2, timeout = 1)
fun <- function(x){
    a <- 0
    for(i in 1:100000){
        a <- a + runif(10000)
    }
}
bplapply(1:2, fun, BPPARAM = p)
```

I do not know why `Sys.sleep` does not trigger the time limit but it looks like the function works for the non-trivial code. Here is a related discussion(but in the discussion they still be able to trigger it, just at the wrong time)

https://stackoverflow.com/questions/16576595/settimelimit-fails-to-terminate-idle-call-in-r
