### ISSUE TITLE
Having issue with installing the BiocParallel

### ISSUE THREAD

**Issue by DrSunYi** [Bioconductor/BiocParallel#208]
BiocManager::install("BiocParallel" , force = TRUE )

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.0 (2022-04-22 ucrt)
Installing package(s) 'BiocParallel'

  There is a binary version available but the source version is later:
             binary source needs_compilation
BiocParallel 1.30.0 1.30.2              TRUE

installing the source package ‘BiocParallel’

trying URL 'https://bioconductor.org/packages/3.15/bioc/src/contrib/BiocParallel_1.30.2.tar.gz'
Content type 'application/x-gzip' length 895354 bytes (874 KB)
downloaded 874 KB

* installing *source* package 'BiocParallel' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-42~1.0/include" -DNDEBUG  -I'C:/Users/ioo10/AppData/Local/R/win-library/4.2/BH/include'   -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c ipcmutex.cpp -o ipcmutex.o
sh: line 1: g++: command not found
make: *** [C:/PROGRA~1/R/R-42~1.0/etc/x64/Makeconf:259: ipcmutex.o] Error 127
ERROR: compilation failed for package 'BiocParallel'
* removing 'C:/Users/ioo10/AppData/Local/R/win-library/4.2/BiocParallel'

The downloaded source packages are in
	‘C:\Users\ioo10\AppData\Local\Temp\Rtmp6PbMjX\downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘BiocParallel’ had non-zero exit status

**Comment by DrSunYi** [comment]
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remotes_2.4.2       BiocManager_1.30.18

loaded via a namespace (and not attached):
[1] compiler_4.2.0 tools_4.2.0    curl_4.3.2     renv_0.15.4

**Comment by DrSunYi** [comment]
Your help will be highly appreciated!

**Comment by vjcitn** [comment]
Hi, the essence of the error is `sh: line 1: g++: command not found`, and to solve this you need to follow the instructions at [the Rtools page](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html).  But there is no reason for this to be happening unless you specifically want to install "from source" -- you should install the binary version of BiocParallel.  Your question really should be posed to support.bioconductor.org as this is not a problem with BiocParallel.

**Comment by mtmorgan** [comment]
Usually the binary and source distributions are in sync and you would not be offered the opportunity to install from source, but the [build report][1] shows that only the windows binary builds are failing, and must have done so for all the builds since at least May 7 (the last commit seen by the build system). The error reported is usually transient, but something else might be going on -- @Jiefei-Wang do you have any ideas / able to reproduce? The [specifics of the platform][2] indicate that it is the R-4.2.0 'ucrt' build on Windows.

The difference between source and binary are summarized in the NEWS file
```
BUG FIXES

    ...

    o (v 1.30.1) suppress package startup messages on workers
    https://github.com/Bioconductor/BiocParallel/issues/198

    o (v 1.30.1) coerce timeout to integer (typically from numeric)
    https://github.com/Bioconductor/BiocParallel/issues/200

    o (v 1.30.2) resetting bpRNGseed() after bpstart() is reproducible
    https://github.com/Bioconductor/BiocParallel/pull/204
```
The first is a bug that produces an annoying amount of output when workers start up, the others are very edge case. Likely you can install the binary version now and update when it finally propagates

[1]: https://bioconductor.org/checkResults/release/bioc-LATEST/BiocParallel/palomino3-checksrc.html
[2]: https://bioconductor.org/checkResults/release/bioc-LATEST/palomino3-NodeInfo.html

**Comment by DrSunYi** [comment]
Problem soloved!

I removed rvns, uninstalled Rtools 4.0 and reinstalled Rtools 4.2.

Then, BiocParallel was installed successfully.

Thank you Vince Carey and Vince Carey

**Comment by Jiefei-Wang** [comment]
The problem is that I cannot see where the error is in the build report... 

There are a few deactivated tests in the unit test but they are not failures and would not be treated as errors in `R CMD check`. 

We also have a connection error but it seems like this would not be treated as a true error either. I've tried to reproduce it with the same commit hash but with no success. I can get the same errors from the unit test but my `R CMD check` succeed. Here is a part of my output
```
* checking for unstated dependencies in 'tests' ... OK                                                                  
* checking tests ...                                                                                                      
   Running 'test.R'                                                                                                       
    OK                                                                                                                     
* checking for unstated dependencies in vignettes ... OK                                                                
* checking package vignettes in 'inst/doc' ... OK                                                                       
* checking running R code from vignettes ... SKIPPED                                                                    
* checking re-building of vignette outputs ... SKIPPED                                                                  
* checking PDF version of manual ... OK                                                                                 
* DONE 
```
The true issue is still a mystery
