### ISSUE TITLE
bpslots to query for availability of nested parallel cores

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/BiocParallel#36]
From Michael Lang:

Consider the task to align N sequence files (each containing millions of
reads) to a reference genome. We want to perform this in R using
parallelization on a parallel backend with C CPU cores.

If N is large compared to the number of CPU cores C, efficient
parallelization can be achieved by distributing the N sequence files to
the C workers, which will each perform single-threaded alignments.

The use-case arises when N is smaller than C. I further assume that
multiple cores are available on a single physical compute node, which I
think is typical these days. Because the alignment algorithm is able to
run multiple parallel threads, efficient parallelization could be
achieved by engaging N workers, each using P parallel threads.
Optimally, P is such that P*N == C, so P could be close to C/N. In
practice, P is the (minimal) number of cores available on a physical
node. The use case could be thought of as "nested parallelization"
(across workers and across threads).

It is a very typical case at our institute and for our collaborators at
the University of Basel: N is often below 20 (the number of samples in a
sequencing experiment, e.g. 3 genotypes times 3 replicates), and C is
well over 100 (and can be as high as 8000 on the University cluster,
with many 64-core nodes). We think that splitting one sequence file into
smaller chunks (thereby increasing N) would not be a feasible solution
(slow IO performance).

I was hoping that there would be an abstraction allow me to write
parallel code that would be independent of the parallel backend. I am
very excited about BiocParallel and bpworkers(), which is a great way
(for QuasR) to learn about the "first level" of the nested
parallelization, in a manner that is independent of the parallel
backend. What I am missing is a standardized way to also query
BiocParallel for the second level of the nested parallelization (the
number of parallel threads that can run on one worker), e.g. using a
function such as bpslots().

When using a BatchJobs backend, I imagine bpslots() would return a value
that is comparable to the value in the NSLOTS environment variable on a
SGE cluster node. The value would be set by the user when creating the
instance of BatchJobsParam(), similarly as it is now done with "workers":

    prm <- BatchJobsParam(workers=n, slots=s, ...)

On other backends, some convention would have to be agreed on, e.g.
that bpslots() returns:
   1L for a SerialParam backend
   a user-set value (default: NA) for SnowParam, DoparParam and MulticoreParam backends

Currently, QuasR tries to guess bpworkers() and bpslots() by querying
the parallel::SOCKcluster object provided by the user, similar as in the
following example (xenon2 and xenon3 are local machine names):

    > library(parallel)
    > cl <- makeCluster(rep(c("xenon2","xenon3"),each=3))
    > cl
    socket cluster with 6 nodes on hosts 'xenon2', 'xenon3'
    > tnn <- table(unlist(clusterEvalQ(cl, Sys.info()['nodename'])))
    > tnn
    xenon2.fmi.ch xenon3.fmi.ch
                3             3
    > length(tnn) # bpworkers()
    [1] 2
    > min(tnn) # bpslots()
    [1] 3

This only works for this particular type of parallel backend. If we want
to support multiple parallel backends, we will have to write
backend-specific code into QuasR. Alternatively, if this is abstracted
by BiocParallel with bpslots(), QuasR could parallelize across
bpworkers() nodes, using up to bpslots() parallel threads on each of them.

**Comment by vobencha** [comment]
I believe these were addressed with the implementation of the list of BiocParams and register/registered.

**Comment by lawremi** [comment]
Sort of. This thread sort of diverged from the initial motivation. At least one aspect of this was that we need an abstract way to obtain the resources available to a worker. For example, let's say we launch a job via BatchJobs, giving it a resource specification for the number of cores per worker. The backend will somehow configure the environment to inform the worker of the available resources. For example, LSF sets an environment variable for the number of cores. It would be great if BiocParallel could automatically use that as the default (maximum?) number of cores for the multicore backend. I realize that we can set the number of cores on the MulticoreParam in the BiocParam list, but that is not communicated to the scheduler.

All of this is sort of moot for us, because BatchJobsParam has never worked reliably for us on our cluster, and with the move to SnowParam, multicore does not work either :( We're back in the world of adhoc solutions.
