### ISSUE TITLE
Loading packages within bplapply instance

### ISSUE THREAD

**Issue by asenabouth** [Bioconductor/BiocParallel#68]
Hi,
I'm currently developing a package where a function I created calls bplapply, which in turn is supplied with a function from another package that is no longer being supported. I realised while troubleshooting my function that the other function didn't have the dependancy added to the namespace.

I recall there was another parallel package that allowed users to load packages into parallel instances. Is it possible with BiocParallel? I have a workaround which used a library call within the function itself, but I would like to avoid doing that as it brings up a warning about using the library call during R CMD CHECK.

Thanks!

**Comment by mtmorgan** [comment]
In the future, ask support questions on the [Bioconductor support site][1] or for package development on the Bioc-devel [mailing list][2].

Probably it would help to have a specific example (e.g., a github repo), because it can be very confusing to keep multiple functions in multiple packages straight.

I think that if package A has function bar() and imports B::foo(), and bar() is used as `FUN` in `bplapply()` and calls, directly or indirectly foo(), then there is no need to do anything special to ensure availability of foo.

If the function foo() is somehow not imported into the namespace, then one can either invoke it directly as `B::foo()` or in steps, e.g., `nmspc = loadNamespace("B"); nmspc$foo()`.

If the problem is that foo() calls a function C::baz(), but B does not import baz() and instead relies on `baz()` being on the `search()` path, then really there is no choice but to place C on the search path of the worker (e.g., by `require("C")`). But this seems to be working around a problem in B (not importing baz from C) and should be remedied at that level (using packages with correctly formulated dependencies).

Hope that helps...

[1]: https://support.bioconductor.org
[2]: https://stat.ethz.ch/mailman/listinfo/bioc-devel

**Comment by asenabouth** [comment]
Great - will use that site from now on for questions. Apologies for the lack of example, but thank you for understanding my question and providing a detailed explanation. Looks like I'll have to keep the require function for package C in function A::bar(). Thanks again!
