### ISSUE TITLE
Helper function to detect if backend is single-machine

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/BiocParallel#76]
It can be helpful to know if the backend is single-machine (e.g., https://github.com/Bioconductor/DelayedArray/issues/20#issuecomment-390747227). From reading Section 4.1 'Single machine' of http://bioconductor.org/packages/devel/bioc/vignettes/BiocParallel/inst/doc/Introduction_To_BiocParallel.pdf, I derived the following:

```r
.isSingleMachineBackend <- function(BPPARAM) {
    if (is(BPPARAM, "SerialParam") || is(BPPARAM, "MulticoreParam")) {
        return(TRUE)
    } else if (is(BPPARAM, "SnowParam")) {
        if (is.numeric(bpworkers(BPPARAM)) &&
            BPPARAM$.clusterargs$type == "SOCK") {
            return(TRUE)
        } else {
            return(FALSE)
        }
    } else if (is(BPPARAM, "DoparParam")) {
        # TODO: Can't figure this one out
    } else {
        return(FALSE)
    }
}
```

I can't quite figure out the logic for _DoparParam_. Could something like this be added to **BiocParallel**?

**Comment by mtmorgan** [comment]
I would instead take the approach of trying to determine the computer's host name, e.g., via `Sys.info()["nodename"]` (but I'm forgetting something about when this fails...), perhaps as part of a unique id, e.g., `ipcid(Sys.info()["nodename"])`. This would be useful if, for instance, there were both local and and non-local processes in a socket cluster.

I also sketched out a [distributed lock][1] using httpuv, where the 'server' would run in one process (e.g., on the host machine) and the 'client' in separate processes. It can be tested by sourcing the server in one R instance, and sourcing the client in another. It would not be hard to further wrap this so that the `runServer()` command was started in a forked (via `mcparallel()`) or spawned (by starting a SNOW cluster of size 1 and evaluating there) or maybe using the `later` paradigm from httpuv. The challenge here is that this would be difficult to make robust -- e.g., the server has to be able to listen on particular ports, and the clients need to talk over those ports, but maybe that robustness is required in at least some of the back-ends.
[1]: https://gist.github.com/mtmorgan/b5a2b90d0ace9ad0be5eb179e26b56f1
