### ISSUE TITLE
Huge overhead of bplapply(..., BPPARAM=SnowParam()) on Windows

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocParallel#78]
I'm observing a huge overhead when using `bplapply()` with the `SnowParam()` backend on Windows:
```
library(DelayedArray)
m <- matrix(runif(60) > 0.5, ncol=6)
grid <- blockGrid(m, block.maxlen=6)
system.time(blockApply(m, identity, grid=grid, BPPARAM=SerialParam()))
#   user  system elapsed
#   0.03    0.00    0.03
system.time(blockApply(m, identity, grid=grid, BPPARAM=SnowParam()))
#   user  system elapsed
#    0.05    0.00   14.12
```
Sorry that the above code uses `blockApply()` and not `bplapply()` directly. Here is why: `blockApply()` is a simple wrapper to `bplapply()` and the above calls to `blockApply()` are just doing `bplapply(seq_along(grid), function(b) read_block(m, grid[[b]]))`. However, this code doesn't work with the `SnowParam()` backend:
```
system.time(bplapply(seq_along(grid), function(b) read_block(m, grid[[b]]), BPPARAM=SerialParam()))
#   user  system elapsed
#   0.03    0.00    0.03
system.time(bplapply(seq_along(grid), function(b) read_block(m, grid[[b]]), BPPARAM=SnowParam()))
# Error: BiocParallel errors
#   element index: 1, 2, 3, 4, 5, 6, ...
#  first error: could not find function "read_block"
# Timing stopped at: 0.03 0.02 2.5
system.time(bplapply(seq_along(grid), function(b) DelayedArray::read_block(m, grid[[b]]), BPPARAM=SnowParam()))
# Error: BiocParallel errors
#   element index: 1, 2, 3, 4, 5, 6, ...
#   first error: object of type 'closure' is not subsettable
# Timing stopped at: 0 0.02 4.42
```
Note that this code also fails on Linux with the `SnowParam()` backend but works with all other backends (`SerialParam()`, `MulticoreParam()`, `BatchtoolsParam()`, etc...)

Are these known issues? Are there plans to remedy them?

`bplapply()` is at the core of block processing in DelayedArray and running the DelayedArray unit tests triggers hundreds of `bplapply()` calls. Unfortunately `bplapply()` uses the `SnowParam()` backend by default on Windows, causing `R CMD check` to timeout when running the unit tests on this platform: https://bioconductor.org/checkResults/3.8/bioc-LATEST/DelayedArray/tokay1-checksrc.html

What should I do about this? I'm tempted to disable parallel evaluation on Windows by putting something like `if (.Platform$OS.type == "windows") register(SerialParam())` in DelayedArray's `.onLoad` hook. Comments?

Thanks!

```
> sessionInfo()
R version 3.5.1 Patched (2018-07-24 r75008)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2012 R2 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] DelayedArray_0.7.21 BiocParallel_1.15.8 IRanges_2.15.16
[4] S4Vectors_0.19.19   BiocGenerics_0.27.1 matrixStats_0.54.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1 snow_0.4-2
```

**Comment by mtmorgan** [comment]
`SnowParam()` processes are completely independent.

Part of the speed issue is that DelayedArray needs to be loaded on the worker.

This 
```
bplapply(seq_along(grid), function(b) DelayedArray::read_block(m, grid[[b]]), BPPARAM=SnowParam())
```
fails because `m` and `grid` are not present on the worker (the specific error is because R is resolving `grid` to `graphics::grid`. The requirement is that the `FUN` in `bplapply()` is strictly functional, so

```
bplapply(
    seq_along(grid),
    function(b, m, grid) {
        DelayedArray::read_block(m, grid[[b]])
    }, m, grid, BPPARAM = SnowParam()
)
```
but one wants to be careful about the size of the objects sent to the workers. They are serialized and transmitted over a socket connection. Serialized objects may be too large, and the transfer costs can be overwhelming.

As written above, each time `bplapply()` is invoked it sees a new `SnowParam()`, so starts up independent processes. Consequently each call to `bplapply()` pays the cost of loading DelayedArray. A different strategy is to `open(bpparam())` and NOT pass `BPPARAM=` to `bplappy()`. This starts the default cluster, and it remains started for the duration of the R session -- DelayedArray gets loaded on the first `bplappy()`, but on subsequent `bplapply()` it's already available.

**Comment by mtmorgan** [comment]
Some related discussion on avoiding sending (potentially large) `m` to the workers on the [community slack][1] (see also the replies) lead to this [gist][2] where the realization is moved to the manager using `bpiterate()`.

[1]: https://community-bioc.slack.com/archives/C35BSB5NF/p1529524471000501
[2]: https://gist.github.com/LTLA/7cf5d6231a9616084803429348760760

**Comment by hpages** [comment]
Thanks for all the useful tips. Makes a lot of sense to use callback functions that are pure functions. I've been putting this in practice for a while now.
